# Generated by Django 2.2.3 on 2019-07-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="admin_type",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("ASSISSTANT", "Assisstant"),
                ],
                max_length=20,
            ),
        ),
    ]
