# Generated by Django 2.2.3 on 2019-07-28 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_auto_20190726_0401"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(13),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
