# Generated by Django 2.2.4 on 2019-08-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_auto_20190820_0517"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Note",
        ),
    ]
