# Generated by Django 2.2.4 on 2019-10-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_delete_note"),
        ("account", "0010_auto_20190817_2055"),
    ]

    operations = []
