# Generated by Django 2.2.4 on 2019-10-13 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0014_merge_20191013_2337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParentNote',
            new_name='Note',
        ),
        migrations.RemoveField(
            model_name='studentnote',
            name='user',
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='InstructorNote',
        ),
        migrations.DeleteModel(
            name='StudentNote',
        ),
    ]
