# Generated by Django 2.2.3 on 2019-11-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20191108_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
