# Generated by Django 2.2.3 on 2019-11-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_parent_secondary_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="parent",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="parent",
            name="secondary_phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
