# Generated by Django 2.2.3 on 2019-11-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_auto_20191115_0607"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructor",
            name="age",
        ),
    ]
