# Generated by Django 2.2.3 on 2019-11-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_instructor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='account_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Admin')], default='ADMIN', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='account_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Admin')], default='INSTRUCTOR', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='account_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Admin')], default='PARENT', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='account_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
            preserve_default=False,
        ),
    ]
