# Generated by Django 2.2.4 on 2019-12-15 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_auto_20191115_1034"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monday_start_time", models.TimeField(blank=True, null=True)),
                ("monday_end_time", models.TimeField(blank=True, null=True)),
                ("tuesday_start_time", models.TimeField(blank=True, null=True)),
                ("tuesday_end_time", models.TimeField(blank=True, null=True)),
                ("wednesday_start_time", models.TimeField(blank=True, null=True)),
                ("wednesday_end_time", models.TimeField(blank=True, null=True)),
                ("thursday_start_time", models.TimeField(blank=True, null=True)),
                ("thursday_end_time", models.TimeField(blank=True, null=True)),
                ("friday_start_time", models.TimeField(blank=True, null=True)),
                ("friday_end_time", models.TimeField(blank=True, null=True)),
                ("saturday_start_time", models.TimeField(blank=True, null=True)),
                ("saturday_end_time", models.TimeField(blank=True, null=True)),
                ("sunday_start_time", models.TimeField(blank=True, null=True)),
                ("sunday_end_time", models.TimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="account.Instructor",
                    ),
                ),
            ],
        ),
    ]
