# Generated by Django 2.2.9 on 2020-01-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0027_auto_20200103_2231"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructor",
            old_name="languages",
            new_name="language",
        ),
    ]
