# Generated by Django 2.2.10 on 2020-02-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_parent_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='balance',
        ),
    ]
