# Generated by Django 2.2.10 on 2020-02-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_instructoroutofoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructoroutofoffice',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
