# Generated by Django 2.2.10 on 2020-02-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_instructoroutofoffice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructoroutofoffice',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
