# Generated by Django 2.2.12 on 2020-06-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20200515_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('receptionist', 'Receptionist'), ('assistant', 'Assistant')], max_length=20),
        ),
    ]
