# Generated by Django 3.0.3 on 2020-07-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_auto_20200722_0128'),
    ]

    operations = [
    ]
