# Generated by Django 3.0.3 on 2020-07-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_merge_20200726_1740'),
        ('account', '0041_auto_20200725_0334'),
    ]

    operations = [
    ]
