# Generated by Django 2.2.17 on 2021-01-20 04:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0043_auto_20201003_1659"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Note",
            new_name="AccountNote",
        ),
    ]
