# Generated by Django 2.2.12 on 2020-10-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_auto_20201003_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(default='hi@omou.com', max_length=70, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
