# Generated by Django 2.2.16 on 2021-03-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_auto_20210120_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='google_auth_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
