# Generated by Django 2.2.19 on 2021-03-01 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('account', '0044_auto_20210120_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='onboarding.Business'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='onboarding.Business'),
        ),
        migrations.AddField(
            model_name='parent',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='onboarding.Business'),
        ),
        migrations.AddField(
            model_name='student',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='onboarding.Business'),
        ),
    ]
