# Generated by Django 2.2.19 on 2021-05-01 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
        ("account", "0045_admin_google_auth_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="onboarding.Business",
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="onboarding.Business",
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="onboarding.Business",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="onboarding.Business",
            ),
        ),
    ]
