# Generated by Django 2.2.16 on 2021-04-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0045_admin_google_auth_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="google_auth_email",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
