# Generated by Django 3.0.3 on 2021-04-24 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('account', '0046_add_business_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='onboarding.Business'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='onboarding.Business'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='onboarding.Business'),
        ),
        migrations.AlterField(
            model_name='student',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='onboarding.Business'),
        ),
    ]
