# Generated by Django 2.2.20 on 2021-05-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_auto_20210501_2226'),
        ('account', '0046_admin_google_auth_email'),
    ]

    operations = [
    ]
