# Generated by Django 2.2.1 on 2019-06-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190604_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursecategory',
            new_name='course_category',
        ),
    ]
