# Generated by Django 2.2.3 on 2019-11-10 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_auto_20190728_1915"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="days",
            new_name="days_of_week",
        ),
        migrations.RemoveField(
            model_name="course",
            name="schedule",
        ),
        migrations.AddField(
            model_name="course",
            name="end_time",
            field=models.TimeField(
                default=datetime.datetime(2019, 11, 10, 2, 58, 30, 352989, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="start_time",
            field=models.TimeField(
                default=datetime.datetime(2019, 11, 10, 2, 59, 6, 799875, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
