# Generated by Django 2.2.4 on 2019-08-17 04:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='course.Course'),
            preserve_default=False,
        ),
    ]
