# Generated by Django 2.2.3 on 2019-11-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_start_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='days_of_week',
            new_name='day_of_week',
        ),
    ]
