# Generated by Django 2.2.4 on 2019-08-17 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_session_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_date_time',
            field=models.DateTimeField(default='2019-08-17T19:00:54.995Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start_date_time',
            field=models.DateTimeField(default='2019-08-17T19:00:54.995Z'),
            preserve_default=False,
        ),
    ]
