# Generated by Django 2.2.3 on 2019-11-15 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20191114_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
