# Generated by Django 2.2.3 on 2019-11-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20191115_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='0', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
