# Generated by Django 2.2.3 on 2019-11-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0012_auto_20191115_0607"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="payment",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
