# Generated by Django 2.2.4 on 2019-12-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20191201_2222'),
        ('course', '0015_coursenoteaccounttag_coursenotecoursetag'),
    ]

    operations = [
    ]
