# Generated by Django 2.2.7 on 2020-01-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20200101_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('C', 'Class'), ('S', 'Small Group'), ('T', 'Tutoring')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('E', 'Elementary School Level'), ('M', 'Middle School Level'), ('H', 'High School Level'), ('C', 'College Level')], max_length=1, null=True),
        ),
    ]
