# Generated by Django 2.2.3 on 2020-01-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0022_auto_20200102_1921"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
