# Generated by Django 2.2.12 on 2020-05-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_optional_day_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subject',
            new_name='title',
        ),
    ]
