# Generated by Django 2.2.16 on 2020-11-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_auto_20201116_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseavailability',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
