# Generated by Django 2.2.15 on 2020-12-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_auto_20201129_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='google_enrollment_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
