# Generated by Django 2.2.15 on 2020-12-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_course_course_link_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='google_class_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
