# Generated by Django 3.0.3 on 2020-12-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0033_course_google_class_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="invite_status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("unsent", "Unsent"),
                    ("accepted", "Accepted"),
                    ("invalid_email", "Invalid_Email"),
                ],
                default="unsent",
                max_length=13,
            ),
        ),
    ]
