# Generated by Django 2.2.7 on 2019-12-30 08:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('amount_type', models.CharField(choices=[('percent', 'percent'), ('fixed', 'fixed')], default='fixed', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DateRangeDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pricing.Discount')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            bases=('pricing.discount',),
        ),
        migrations.CreateModel(
            name='MultiCourseDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pricing.Discount')),
                ('num_sessions', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1000)])),
            ],
            bases=('pricing.discount',),
        ),
        migrations.CreateModel(
            name='PaymentMethodDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pricing.Discount')),
                ('payment_method', models.CharField(max_length=50)),
            ],
            bases=('pricing.discount',),
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('hourly_tuition', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('academic_level', models.CharField(choices=[('elementary_lvl', 'Elementary'), ('middle_lvl', 'Middle'), ('high_lvl', 'High'), ('college_lvl', 'College')], default='elementary_lvl', max_length=20)),
                ('course_type', models.CharField(choices=[('tutoring', 'Tutoring'), ('small_group', 'Small group'), ('class', 'Class')], default='tutoring', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='course.CourseCategory')),
            ],
        ),
    ]
