# Generated by Django 2.2.8 on 2019-12-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0018_auto_20191209_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('hourly_tuition', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='StaticPrice',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pricing.Price')),
            ],
            bases=('pricing.price',),
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pricing.Price')),
                ('academic_level', models.CharField(blank=True, choices=[('ELEMENTARY_LVL', 'Elementary'), ('MIDDLE_LVL', 'Middle'), ('HIGH_LVL', 'High'), ('COLLEGE_LVL', 'College')], max_length=10, null=True)),
                ('min_capacity', models.IntegerField(blank=True, null=True)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.CourseCategory')),
            ],
            bases=('pricing.price',),
        ),
    ]
