# Generated by Django 2.2.8 on 2019-12-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_auto_20191215_0135"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fee",
        ),
    ]
