# Generated by Django 2.2.8 on 2019-12-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0005_auto_20191228_0048"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
