# Generated by Django 2.2.14 on 2020-07-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_auto_20200102_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
    ]
