# Generated by Django 2.2.19 on 2021-05-26 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_pricerule_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerule',
            name='academic_level',
        ),
    ]
