# Generated by Django 2.2.19 on 2021-05-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0014_remove_pricerule_academic_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricerule",
            name="all_instructors_apply",
            field=models.BooleanField(default=True),
        ),
    ]
