# Generated by Django 2.2.19 on 2021-05-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20210502_0028'),
        ('pricing', '0015_pricerule_all_instructors_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerule',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='onboarding.Business'),
        ),
    ]
