# Generated by Django 2.2.19 on 2021-06-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0020_remove_tuitionprice_is_retired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionrule',
            name='all_instructors_apply',
        ),
        migrations.AddField(
            model_name='tuitionprice',
            name='all_instructors_apply',
            field=models.BooleanField(default=True),
        ),
    ]
