# Generated by Django 2.2.19 on 2021-07-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_invoice_payment_due_date'),
        ('pricing', '0021_auto_20210626_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multicoursediscount',
            name='discount_ptr',
        ),
        migrations.RemoveField(
            model_name='paymentmethoddiscount',
            name='discount_ptr',
        ),
        migrations.DeleteModel(
            name='DateRangeDiscount',
        ),
        migrations.DeleteModel(
            name='MultiCourseDiscount',
        ),
        migrations.DeleteModel(
            name='PaymentMethodDiscount',
        ),
    ]
