# Generated by Django 2.2.4 on 2019-08-17 05:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0007_session_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('AMOUNT', 'Amount'), ('PERCENTAGE', 'Percentage')], max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sessions', models.ManyToManyField(to='course.Session')),
            ],
        ),
    ]
