# Generated by Django 2.2.4 on 2019-08-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='end_date_time',
            field=models.DateTimeField(default='2019-08-17T19:00:54.995Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='start_date_time',
            field=models.DateTimeField(default='2019-08-17T19:00:54.995Z'),
            preserve_default=False,
        ),
    ]
