# Generated by Django 2.2.4 on 2019-08-17 04:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190728_1915'),
        ('course', '0007_session_course'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('WAIVED', 'Waived')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Student')),
            ],
        ),
    ]
