# Generated by Django 2.2.4 on 2019-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_sessionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_time',
            field=models.DateTimeField(default='2019-08-17T19:00:54.995Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionpayment',
            name='date_time',
            field=models.DateTimeField(default='2019-08-17T19:00:54.995Z'),
            preserve_default=False,
        ),
    ]
