# Generated by Django 2.2.4 on 2019-08-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190817_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionpayment',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
