# Generated by Django 2.2.4 on 2019-08-17 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20190817_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionpayment',
            name='student',
        ),
        migrations.AddField(
            model_name='sessionpayment',
            name='payment',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='payment.Payment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('CHECK', 'Check'), ('ACCOUNT_CREDIT', 'Account Credit')], max_length=5),
        ),
    ]
