# Generated by Django 2.2.4 on 2019-08-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20190817_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('CHECK', 'Check'), ('ACCOUNT_CREDIT', 'Account Credit')], max_length=14),
        ),
    ]
