# Generated by Django 2.2.12 on 2020-05-22 02:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_id", models.CharField(max_length=50)),
                (
                    "sender",
                    models.EmailField(default="omoudev@gmail.com", max_length=254),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                ("response_status", models.CharField(max_length=10)),
                ("response_body", models.CharField(max_length=1000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
