# Generated by Django 2.2.12 on 2020-05-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0002_smsnotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsnotification",
            name="response_body",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="smsnotification",
            name="response_status",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
