# Generated by Django 2.2.12 on 2020-06-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0003_auto_20200529_0220"),
    ]

    operations = [
        migrations.RenameField(
            model_name="email",
            old_name="response_status",
            new_name="status",
        ),
    ]
