# Generated by Django 3.0.3 on 2020-07-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_annoucement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annoucement',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='annoucement',
            old_name='user',
            new_name='poster',
        ),
        migrations.AddField(
            model_name='annoucement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='annoucement',
            name='subject',
            field=models.TextField(),
        ),
    ]
