# Generated by Django 2.2.12 on 2020-07-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_auto_20200725_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentnotificationsettings',
            name='course_requests_sms',
            field=models.BooleanField(default=False),
        ),
    ]
