# Generated by Django 3.0.3 on 2020-07-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_announcement'),
        ('comms', '0006_auto_20200725_0550'),
    ]

    operations = [
    ]
