# Generated by Django 3.0.3 on 2020-07-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0007_merge_20200726_1740'),
        ('comms', '0007_parentnotificationsettings_course_requests_sms'),
    ]

    operations = [
    ]
