# Generated by Django 2.2.14 on 2021-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0008_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentnotificationsettings",
            name="missed_session_reminder_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="parentnotificationsettings",
            name="missed_session_reminder_sms",
            field=models.BooleanField(default=False),
        ),
    ]
