# Generated by Django 2.2.3 on 2020-01-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0024_instructoravailability'),
        ('course', '0020_auto_20200101_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('course_credit', 'Course Credit'), ('credit_card', 'Credit Card')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sessions', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Enrollment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Payment')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollments',
            field=models.ManyToManyField(through='invoice.Registration', to='course.Enrollment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Parent'),
        ),
    ]
