# Generated by Django 2.2.3 on 2020-01-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='enrollments',
            field=models.ManyToManyField(related_name='payment_list', through='invoice.Registration', to='course.Enrollment'),
        ),
    ]
