# Generated by Django 2.2.7 on 2020-02-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0005_auto_20200225_0516"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="base_amount",
            new_name="sub_total",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="total_amount",
            new_name="total",
        ),
    ]
