# Generated by Django 2.2.7 on 2020-03-22 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_auto_20200102_1921'),
        ('invoice', '0006_auto_20200225_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Discount')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Payment')),
            ],
        ),
    ]
