# Generated by Django 2.2.20 on 2021-08-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_invoice_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('canceled', 'Canceled')], default='unpaid', max_length=20),
        ),
    ]
