# Generated by Django 2.2.4 on 2019-11-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
