# Generated by Django 2.2.3 on 2019-11-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_session_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='end_time',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='start_time',
            new_name='start_datetime',
        ),
    ]
