# Generated by Django 2.2.3 on 2020-01-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20200103_2235'),
        ('scheduler', '0003_auto_20191128_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.Instructor'),
        ),
    ]
