# Generated by Django 2.2.7 on 2020-01-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_session_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
