# Generated by Django 2.2.14 on 2020-10-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_auto_20201003_1659'),
        ('scheduler', '0008_sessionnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(None, ''), ('present', 'Present'), ('tardy', 'Tardy'), ('absent', 'Absent')], default=None, max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Student')),
            ],
        ),
    ]
