# Generated by Django 2.2.16 on 2020-11-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0029_auto_20201116_1018"),
        ("scheduler", "0008_sessionnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="availability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="course.CourseAvailability",
            ),
            preserve_default=False,
        ),
    ]
