# Generated by Django 2.2.14 on 2020-10-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20201012_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[(None, ''), ('present', 'Present'), ('tardy', 'Tardy'), ('absent', 'Absent')], default='', max_length=7),
        ),
    ]
