# Generated by Django 2.2.20 on 2021-08-04 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_course_business'),
        ('account', '0047_merge_20210508_1931'),
        ('scheduler', '0011_session_sent_missed_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('request_status', models.CharField(choices=[('submitted', 'Submitted'), ('pending_instructor_approval', 'Pending Instructor Approval'), ('pending_admin_approval', 'Pending Admin Approval')], max_length=50)),
                ('invoice_setting', models.CharField(choices=[('manual', 'Manual'), ('subscription', 'Subscription')], max_length=20)),
                ('course_topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.CourseCategory')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.Instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Student')),
            ],
        ),
    ]
