# Generated by Django 2.2.14 on 2020-10-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20201012_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('unset', ''), ('present', 'Present'), ('tardy', 'Tardy'), ('absent', 'Absent')], default='unset', max_length=7),
        ),
    ]
